<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <AssemblyName>FxDbg.Breakpoint.Probe</AssemblyName>
    <RootNamespace>FxDbg.Breakpoint.Probe</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClrDebug" Version="0.4.2" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
