<Project>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net40'">
    <LangVersion>7.3</LangVersion>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net40'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies"
                      Version="1.0.3"
                      PrivateAssets="all" />
  </ItemGroup>
</Project>
