<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FxDbg.Core\FxDbg.Core.csproj" />
    <PackageReference Include="Microsoft.DiaSymReader" Version="2.2.11" />
    <PackageReference Include="Microsoft.DiaSymReader.Native" Version="17.12.0-beta1.24603.5" />
    <PackageReference Include="System.Reflection.Metadata" Version="8.0.1" />
  </ItemGroup>
</Project>
